# Generated by Django 3.2.9 on 2022-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20220526_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
