# Generated by Django 3.2.9 on 2022-05-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20220526_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
    ]
