# Generated by Django 3.2.9 on 2022-05-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_about_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_proficient', models.CharField(max_length=255)),
                ('language_familiar', models.CharField(max_length=255)),
                ('backend', models.CharField(max_length=255)),
                ('frontend', models.CharField(max_length=255)),
                ('tools', models.CharField(max_length=255)),
            ],
        ),
    ]
