# Generated by Django 3.2.9 on 2022-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='first_language',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='second_language',
            field=models.CharField(default=213123, max_length=255),
            preserve_default=False,
        ),
    ]
