# Generated by Django 3.2.9 on 2022-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=231, max_length=225),
            preserve_default=False,
        ),
    ]
