# Generated by Django 3.2.9 on 2022-05-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uses',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
