# Generated by Django 3.2.9 on 2022-05-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_project_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='api',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
