# Generated by Django 3.2.9 on 2022-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0014_project_schoolp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
