# Generated by Django 3.2.9 on 2022-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
