# Generated by Django 3.2.9 on 2022-06-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0016_project_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='project_image'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='project_image'),
        ),
    ]
