# Generated by Django 3.2.9 on 2022-06-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0017_auto_20220604_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='project_image'),
        ),
    ]
