# Generated by Django 3.2.9 on 2022-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0019_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.CharField(max_length=225),
        ),
    ]
