# Generated by Django 3.2.9 on 2022-06-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0020_alter_education_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='nation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='profession',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
