# Generated by Django 3.2.9 on 2022-06-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0023_auto_20220608_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='linkedin',
            new_name='linked',
        ),
    ]
