# Generated by Django 4.0.4 on 2022-06-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0025_about_graduate'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='nation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
