# Generated by Django 3.2.9 on 2022-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0026_about_nation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
