# Generated by Django 3.2.9 on 2022-06-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0027_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='total_date',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
