# Generated by Django 3.2.9 on 2022-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0029_education_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='education_image')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
