# Generated by Django 3.2.9 on 2023-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0031_education_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
