# Generated by Django 3.2.9 on 2023-02-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0034_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Work_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='work_project')),
                ('image2', models.ImageField(upload_to='work_project')),
                ('image3', models.ImageField(upload_to='work_project')),
                ('image4', models.ImageField(upload_to='work_project')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
