# Generated by Django 3.2.9 on 2023-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0035_auto_20230204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
