# Generated by Django 3.2.9 on 2023-02-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0036_auto_20230204_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
