# Generated by Django 3.2.9 on 2023-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0037_work_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='tech',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
