# Generated by Django 3.2.9 on 2023-02-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0038_work_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
