# Generated by Django 3.2.9 on 2023-02-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0039_work_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
