# Generated by Django 3.2.9 on 2023-02-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0040_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_project',
            name='uat_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
