# Generated by Django 3.2.9 on 2023-03-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0043_about_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='social',
            new_name='facebook',
        ),
    ]
