# Generated by Django 3.2.9 on 2024-03-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0044_rename_social_about_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='country',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
