# Generated by Django 3.2.9 on 2024-03-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0045_work_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='country',
            new_name='address',
        ),
    ]
